### ISSUE TITLE
Handling corrupted data

### ISSUE THREAD

**Issue by airknights** [pda/pheanstalk#111] opened 2015-05-11 13:38 UTC
We had incidents of corrupted data, most probably due to network failure during job entry into queue.  It cut off the job string data about half way.  This resulted in getting the Pheanstalk_Exception_ClientException when CRLF wasn't the last character in the data.

This should be handled at the parser level, as it is still reserving the job, but we don't have a job id to handle this exception gracefully.  A parser should initiate the first line as "job meta data parser" and then do the data part as "job data parser".  Thereby providing the job id of a successful reservation for example.  This allows us to decide to do something else with the job, such as bury it or delete it, or report it in so we can resolve network issues.

Please note the issue I'm talking about is Connection::dispatchCommand function.

**Comment by SamMousa** [comment] 2018-08-30 07:38
@airknights is this issue still relevant?
I'm thinking that if the data got corrupted when entering it into the queue, it is beanstalks responsibility.
If our connection to beanstalk fails when retrieving the data then that's another thing.

**Comment by gopi-ar** [comment] 2018-08-30 07:42
We've seen this often and there's some correlation between unplanned system reboots / beanstalk crashes. We have to telnet into beanstalkd and delete the offending job. Not sure how other clients handle this error, but pheanstalk should probably deal with it gracefully.

**Comment by SamMousa** [comment] 2018-08-30 11:34
Are you guys using persistent connections? If so, please turn try to reproduce without persistent connections enabled.

**Comment by gopi-ar** [comment] 2018-08-30 15:18
On the servers we've seen this issue in, we've used pheanstalk in our long-running workers with persistent set to off.

**Comment by airknights** [comment] 2018-08-30 19:51
This is old issue and is no longer relevant to me.

**Comment by SamMousa** [comment] 2018-08-31 08:30
@gopi-ar when was the last time you saw this?
If it was a long time ago I'd prefer to close this issue for now.

**Closed** 2018-10-05 15:51 UTC
Labels: need more info

**Comment by georaldc** [comment] 2025-03-18 19:52
> We've seen this often and there's some correlation between this issue's occurrence and unplanned system reboots / beanstalk crashes. We have to telnet into beanstalkd and delete the offending job. Not sure how other clients handle this error, but pheanstalk should probably deal with it gracefully.

Sorry to comment on this closed issue, but I just encountered this problem last night. I am using an older v4 version of pheanstalk though due to current usage of PHP 7.3, but connecting to the latest version of beanstalkd. We've been inserting hundreds to thousands of jobs at any given moment for a few years now and a single job somehow got queued where the data was showing as truncated on beanstalkd. Interestingly, after I manually connected to the server and deleted the offending job (which was the only way I could fix this since pheanstalk complains about the missing CRLF bytes and other tools like beanstalk_console do not show the corrupted job at all and also complain similarly), about 3 minutes later beanstalkd crashed with a "segfault, error 4" error. I've seen this happen several times now, where it segfaults once every month or so, so I'm not sure if the corrupted job is somehow related to this (like something building up on beanstalkd that eventually leads to it having a segmentation fault after running nonstop for some time).

Since I use v4, no persistent connections are involved. I did not get any exceptions at the time the corrupted data was inserted so I don't think the SocketSocket implementation was made aware of any failures during its write loop calling socket_write()

**Comment by SamMousa** [comment] 2025-03-18 20:39
Create a new issue please. We will need a reproducible example in the latest version.

> PHP 7.3 reached End-Of-Life on 2021-12-06, and none of the releases listed below are safe to be used.
